### ISSUE TITLE
Do not reused outdated availabilities

### ISSUE THREAD

**Issue by chrisxkeith** [usdigitalresponse/npi-lawyer-client-matching#10]

**Comment by chrisxkeith** [comment]
**Goal**
Allow matching (and re-matching) to return the same result until the ‘asking for confirmation’ emails are sent out. This is consistent with the way the code handles clients.

**Steps**

- Delete all rows in ‘Ranked Availability’’. There may have been unused availabilities, but they are from last week (or whenever the last ‘asking for confirmation’ emails went out).
- Copy from ‘Availability Raw’ all rows timestamped since the most recent email went out.
- Sort by priority (pro bono first, etc.)
- Zero out any duplicates (e.g., if an attorney submitted two availability numbers, use only the most recent).

Matching can now proceed.

**Comment by tkalmanoff** [comment]
This is going to be time-triggered (ie Wednesday at noon) or event-triggered (ie when the email is sent, or when an attorney fills out the availability google form)?

**Comment by chrisxkeith** [comment]
This is part of the process when someone clicks on the "Create Matches".

**Comment by BiblioT3chie** [comment]
We have a workaround for the week of March 24th, and so for previous matched, set them to 0.

**Comment by chrisxkeith** [comment]
Manual testing indicates works as needed.
