### ISSUE TITLE
Add new column to test whether client is eligible to be matched

### ISSUE THREAD

**Issue by chrisxkeith** [usdigitalresponse/npi-lawyer-client-matching#13]

**Comment by BiblioT3chie** [comment]
Testing.

**Comment by chrisxkeith** [comment]
Testing a reply. Zat you, Renee?

**Comment by chrisxkeith** [comment]
If "Associated with Bulk Agreement?" is "Yes", then client should not be available for matching. Don't implement immediately because data may currently be wrong.

**Comment by chrisxkeith** [comment]
Fixed by https://github.com/usdigitalresponse/npi-lawyer-client-matching/commit/de1a2972588dea94c9f5d8049984ac02108d9205 .
