### ISSUE TITLE
Reorder columns in MSCERA Evictions/Applicants spreadsheet so that columns for checking, manually editing, etc. are compressed into one.

### ISSUE THREAD

**Issue by BiblioT3chie** [usdigitalresponse/npi-lawyer-client-matching#19]
For the Evictions/Applicants spreadsheet, https://docs.google.com/spreadsheets/u/0/d/1vnUVqjwj-u6Wn2v4rhBZN5qvfic6Pa7prLMMLGElBzo/edit, the spreadsheet columns are currently ordered in a way that someone has to scroll back and forth to check information. 

By having the columns in the order closest to confirmation, as well as grouping the content by client information, attorney matching information, and clerk and screener confirmation information, it will make the spreadsheet easier to understand and less vulnerable to human error.

Two dependencies to note:
1.) Javascript logic may be impacted by renaming and re-ordering of columns
2.) Zapier will definitely be impacted by additional columns before the right-most column, or renaming, and may also be impacted by format changes

**Comment by BiblioT3chie** [comment]
This will be updated as part of the work being performed by James Anthony to refactor and simplify our data capture and preservation process across USDR/NPI Projects. Our primary work here will be to focus on how it impacts process and if anything should be considered for how the process can improve.

**Comment by jamesant** [comment]
Please lmk if there are specific suggestions here - most of the feedback and reordering I did was focused on the non-evictions-specific fields (shared by utilities and lotto flows), but agree that now's a good time to make any evictions changes too

**Comment by chrisxkeith** [comment]
The work James did satisfies this.
