### ISSUE TITLE
Automating Volunteer Attorney Information Intake

### ISSUE THREAD

**Issue by BiblioT3chie** [usdigitalresponse/npi-lawyer-client-matching#24]
Background: when the project initially began, there was a google sheet available for signing up attorneys, but that was since deprecated. Currently this is a manual process for updating the _Staff List_ tab for the **Matching Sheet**. 

This issue would be to re-create the Google form or have some other intake process beyond just updating the Google Sheet mentioned above.

**Comment by BiblioT3chie** [comment]
This was not asked for by NPI as of Issue creation, and should likely be tagged as out of scope/not to be worked on.

**Comment by chrisxkeith** [comment]
We may actually not want to implement this (or not have the signups go into the Staff List. Steve has talked about having to 'train' attorneys. Perhaps we shouldn't allow anyone to sign up willy-nilly?

**Comment by chrisxkeith** [comment]
Attorney list is now in Airtable.
