### ISSUE TITLE
“Recycling” volunteers who have a conflict or finding a way to reinsert people with bandwidth into the flow instead of having to do it manually

### ISSUE THREAD

**Issue by BiblioT3chie** [usdigitalresponse/npi-lawyer-client-matching#25]
Enhancement/Feature: Finding a way to take a volunteer who has identified that they have a conflict during the matching process, and (1) returning them automatically to the available pool so that (2) they can automatically be re-matched instead of manual editing.

Background: In the part of the attorney-client matching process after a match has been proposed and volunteer attorneys receive an [email](https://docs.google.com/document/d/1mY---dj1gzcuxnI9YQAnb7RNIKIS3nTpWfZWv5uPNZ4/edit#heading=h.cq2yqwt4zblt), they have to confirm they have no conflict. If they do, a clerk or screener at NPI must go in and update the eviction spreadsheet and manually reassign a new attorney to urgent cases, and that volunteer who is available cannot be matched until the next time the matching process is run. 

Benefits: Automatically returning an available attorney to the pool and allowing them be matched to another potential client that week maximizes volunteer time and thus helping individuals facing eviction and minimizes the possibility of human error in the forms.

**Comment by BiblioT3chie** [comment]
Tag for backlog.

**Comment by chrisxkeith** [comment]
Shifting to Airtable
