### ISSUE TITLE
Enhancement: Automating getting correct court dates in for valid court cases and checking the information within

### ISSUE THREAD

**Issue by BiblioT3chie** [usdigitalresponse/npi-lawyer-client-matching#26]
Currently court dates and case numbers in the Eviction spreadsheet are validated by a human checking them, and reliant on the eviction participant to get the information correct. A validation that the case exists and the court date is current/automatically updated would allow optimum matching and prevent human error.

This would require integration with the Shelby County court system.

**Comment by BiblioT3chie** [comment]
Tag for backlog

**Comment by chrisxkeith** [comment]
Still an open question whether someone would still have to manually check the dates/numbers even with automation. In any case, here are questions that would need answering before going much farther.

Questions for Steve Barlow : steve@npimemphis.org
- How do you handle an incorrect case number?
- What error rate have you observed (e.g., % of case dates and numbers that are wrong)?

Questions for Ryan Carroll : ???@???.???
- Can you add code to your scraping code to write the data into a Google Sheet?
- Can you also scrape landlord and tenant data (names, emails, phone numbers and addresses)?
- Are you planning to scrape cases where the court date is in the past?
- Can you filter out cases that have been closed?

Technical / design question(s)
- Should scraped data go into a tab in the Evictions sheet or the Lawyer-Client matching sheet?

**Comment by chrisxkeith** [comment]
Steve emailed:
We have someone with access to the local court data running a scrape of case numbers 3 days a week - and the plan is to populate a new column in the Eviction Sheet v2 with the most up to date court date for that case number.  That same scrape job / data access is also being used to verify, or not, that a case number provided is a valid case number.  The volunteer's name who has been working on that is Ryan Carroll (copied here). 

All that being said - I think our needs on this front will be met once Ryan's project is fully deployed (later this week) - copying Ryan to weigh in on describing his project / status for everyone's information when he has a moment.
