### ISSUE TITLE
Documentation: Document CLIO and KEMPS flows in the User Guide for roles

### ISSUE THREAD

**Issue by BiblioT3chie** [usdigitalresponse/npi-lawyer-client-matching#29]
Documentation Request
One of the steps for the Paralegal/Clerk role is to confirm that each volunteer attorney who has been matched with an attorney who confirms they have no conflicts is either given access to the client files in CLIO (NPI, or non-MALS volunteer) or KEMPS (MALS volunteer). 

Benefit: There is no DRI at this time in NPI for this work, and is reliant exclusively on the diligence of the individual clerk. Having it documented will help new people learn their responsibilities quickly and allow for NPI team members to cover for one another.

**Comment by BiblioT3chie** [comment]
Tag for backlog. Likely out of scope.

**Comment by chrisxkeith** [comment]
Shifting to Airtable
