### ISSUE TITLE
Documentation: Branding improvements for emails, google forms

### ISSUE THREAD

**Issue by BiblioT3chie** [usdigitalresponse/npi-lawyer-client-matching#30]
Review current emails and google forms, and confirm that if there are opportunities to make it clear it's coming from NPI or if there are user questions, that they get an improvement pass. This can help both the recipients act faster and also help the process look more official and polished, and has a very low LOE.

Benefits: adding the logo, links to NPI sites, and making sure standardized language is present across each form.

**Comment by BiblioT3chie** [comment]
Tag as documentation, backlog.

**Comment by BiblioT3chie** [comment]
Have investigated some opportunities that are straightforward. Will confirm via email with Triana and Chris and Hansel, and if ya'll think it's worthwhile, we can check with Steve.

**Comment by chrisxkeith** [comment]
Shifting to Airtable
