### ISSUE TITLE
Before matching, delete all rows from "Awaiting Confirmation" that are more than 5 days old

### ISSUE THREAD

**Issue by tkalmanoff** [usdigitalresponse/npi-lawyer-client-matching#37]

**Comment by chrisxkeith** [comment]
Functionality still unclear to me. The rows in "Awaiting Confirmation" do not affect matching. When "Email Lawyers" is selected from the ESP menu, "Awaiting Confirmation" is cleared of all old rows, and populated with rows containing which cases were emailed to lawyer for confirmation.

**Comment by chrisxkeith** [comment]
This is to handle the case where a lawyer doesn't confirm their availability until 'too late'.

**Comment by chrisxkeith** [comment]
See also https://github.com/usdigitalresponse/npi-lawyer-client-matching/issues/73

**Comment by chrisxkeith** [comment]
Shifting to Airtable
