### ISSUE TITLE
Check with James: Which timezones should our timestamps be defaulting to?

### ISSUE THREAD

**Issue by BiblioT3chie** [usdigitalresponse/npi-lawyer-client-matching#45]
For our Zapier updates for the eviction process, as well as some of the population and logic for the google scripts, we may want to deliberately use Tennessee time or PST  - but which one makes sense? We should check with James and then go through the profile settings of the MSCERA master Google account and the Zapier account.

**Comment by chrisxkeith** [comment]
Shifting to Airtable
