### ISSUE TITLE
"Awaiting Confirmation" matches do not get removed from list

### ISSUE THREAD

**Issue by tkalmanoff** [usdigitalresponse/npi-lawyer-client-matching#48]
The first 5 rows in the image below have already been confirmed or denied and have not been removed from the list. Also (relatedly?) there are 36 blank rows above the matches.

Feel free to downgrade to bug, I have still not yet had my permissions changed.

<img width="416" alt="Screen Shot 2021-04-13 at 8 47 18 PM" src="https://user-images.githubusercontent.com/8835898/114651781-71e9a900-9c99-11eb-82f0-c20498de67d1.png">

**Comment by chrisxkeith** [comment]
So that an attorney doesn't double-confirm (this should remove that case from the dropdown in the google form).
